services:
  mongo:
    image: mongo:8.0.0-rc4-jammy
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=amigoscode
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mongo
    volumes:
      - data:/data
  mongo-express:

    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=amigoscode
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=sa
      - ME_CONFIG_BASICAUTH_PASSWORD=sa
    depends_on:
      - mongo
    restart: always
    networks:
      - mongo

volumes:
  data: {}

networks:
  mongo:
    name: mongo
          